### PR TITLE
Fixed incremental compilation when an imported file is modified

### LINKED ISSUE #72: File compilation when included file change
In our application, we have few (usually 2 or 3) main LESS files producing CSS for web pages. All other files (many) are included into one or more of these main files through `include` statement. However, when we update any of these helpers, main files are not automatically recompiled. It requires to manually change them every time we want them to be up-to-date. This is very inconvenient especially when we are fixing/updating web page design. 

Is there any way how to automatically recompile this main files (defined in `includeFilter`) when their dependencies change?

For easier testing [there is](https://github.com/KarelCemus/sbt-less-test) very simple application with one main file and one included file.

### PR DESCRIPTION
**Pull request by jroper**
Fixes #72

Implemented scripted test to test that it works too.

### CODE REVIEW

File: src/main/resources/lessc.js [hunk 1]
```diff
@@ -99,11 +99,8 @@
                     throwIfErr(e);
 
                     var imports = [];
-                    var files = result.imports;
-                    for (var file in files) {
-                        if (files.hasOwnProperty(file)) {
-                            imports.push(file);
-                        }
+                    for (var i = 0; i < result.imports.length; i++) {
+                        imports.push(result.imports[i]);
```
Comment (huntc) [inline src/main/resources/lessc.js]: So `results.imports` is now an array? I think it was an object before... it was certainly being handled here as an object.

**Comment by huntc** [comment]
LGTM

File: src/main/resources/lessc.js (hunk 1 above)
Comment (jroper) [inline src/main/resources/lessc.js]: I don't know what it was before, but it's definitely an array now.  Plus, here's the way that `lessc` itself uses it:

https://github.com/less/less.js/blob/master/bin/lessc#L412

I figure if we do the same as `lessc` does, we're safe.
